kind: Pod
apiVersion: v1
metadata:
  name: nodejs-pod
  namespace: nodejs
  labels:
    app: nodejs
spec:
   containers:
     - name: nodejs-cont
       image: trainwithshubham/node-app:latest
       ports:
         - containerPort: 8000

